apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/istio/istio'
    targetRevision: 3e5fd5a1d70ea535ad5d18fb66a76c5cce905876
    path: manifests/charts/istio-operator
    helm:
      parameters:
      - name: hub
        value: docker.io/istio
      - name: tag
        value: 1.16.2 # istio/operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
