kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
  encryptedData:
    postgresql-password: AgBcn3wcI3PjHU7jf0Fo5n5hZGzT6POP2KzMHRDPnWAqRfR3pR8it6Cqk3ZKJOvyTvU+w3FdKdPlytAECv551LmWKsu4r1b7PcV7sFDM6hrcI+N73fxKPfL4tk2exwRX50Mlmzq4BpW8KtNwqbhcCDT1018QqoVFmkgXKPgTdmxuEQtGaR6vrHbdehICiQLaFTFj7uGk0YgRfJ+e+W8DArTSvE8RzCstv2Zi2CBG42zNdEP0ACSLrkwXqmjAPz8RaBqUAIXZw8tTeoLojeCzoNvZjB+g5nlacwTaC6XFyNdk8hXsdM7p9NuPytWnKAQ98BuIakpFjHr5VY4bqQKm3w9tZm5ywGlzZSEhMmZIFREOiZpdbnXDYcQCZMm4mZmNeSl/wZn4aJ0qTEqfGN24cnsacIkPIhmJH9AGesvJelyG5hu6awHmzqcOEXY+n6wzaWz7Sl+PXSUjEy8xhqcWS3DUzVG1KOUzbdmZ1DwdyE8wRbLhjnJbj2eVu7pNaDYFq8gujO8Bo+7r3HeSAinOpLrARvIs31ZDgbT6U7ydG76bpdXYXKBT4z5NJlwRRkQfXcCzUriMgu+sy7j++trwyWYQ0A+FSYGIYRKzk05WAMK6tRtcu0dDQ5mzLonzIDZvgH+dVOYwq5VdEd7GSrQTHcJf9i3mTDm/kTLx6u+/lIXMuAtBxDdAYX+USCjXV/9pck/tI2HfZFstOCNw7OGWJIwpT3jDZazZfn3WRsE+G5VLjg==
    postgresql-postgres-password: AgAk3ae0pUW5hTWw/qn1c3kwlUuw+r+b8XW0/bRj1O6BpptxCkfi3CaYgfOgHdI4LEFpyL9plF7noAwZ1Rwozz5Food6AzMDgHV5zucuq4pcjx4hgWETiSrPM1jeWXK4UxfzaZy9y0P2CS8ZclDJGkHCJbIQbvB6EdIqVkRnvOtR0gTXamQmph6DOxDFHTZ0T9lOuDwyxTwPcfBPpoBAfQfCifOK1A35kDRXkZuG0O0kvTvwPBIDdfw4ISi5LzDEaQg2J8luPOWPY8emzdJsVSRGfSQSMy20MLXkuM1DLA+6BJuYOa7CHsupVmqWhAB64KiYVSgo9yjYw0fGiNBAAA23HU9Z2ItHdYkbFe7TngAbOJzwh8LNBkeBaV6MvBrWwu4uMehz9Z3G9j59B2UvBptYDO0vr9wextLxbkQVWVWVsElsUZOi6E6Upz1uAEDznGxtMwo6mwVDwo55xfkWEUqkrRRsvQEGHcdSpgS/7eSTAvAO2YSTBZX4UuA2zeCRv2dgV8aIFrCGF1/WxBwSTBwSRjuB4tpitxjEgrr88zVNUqNt2gSuUSD6+DwkNZw2QplVQsZawKtZl+RX086F2JN9RVO5TvOgg/6oE8mWV/Ctpaau6d4au3/UP7Kt66TR+HqVDGNYs0Zj2G2xLc5ho1KHNIb1VGItJWTESQ+F7h+k5nbbQuwwJBwKnDvTV/PvQW9zlAVeO+14op+1u/XEA40W/I5whaZ74dT+HaQR2/EYbw==
