kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgA9s/J7qe7rW0LJPw+TQReth8eE+e8p7XHE7kXL7W4n5wjl7k15lnRyLv6e9kUdj1kOFPSulxXDwdYQYLuPLnGAqEVP2YwykugaJOS1TsHyk2f/rJcQqYxNzStZvrAc8vrU8UZD2sddySiOgH8rTDLRdOOxC4hRQ23aWSPqLfy7AB1CuQ1wn57RK4hbZFqB9DpHixDUHNJTIeFZwpr7MukrKteEQ18H8v0jw3K2tw9Hr3m7G6uuHSlNVC5b9EV4KS87s9I0/oUJeb0BECt4z+SBT2l8Y0e7lRFDq3ntnp4F+ylrhKFT802pLIZZu/SIOozjS1xo3YRrC0+8SDLvFfK1iqziIs9H/QlHunSIjzRmFJHU2iNjtV+r0HsQx1NRFu2OZlyl4ey8an9b9VCeJr/nkv3ABS5tFgwIO9tjU2ANlAUMB+O6TlSKXBgTM0UnfPJKLUlZaPdjfCBJod4qv/b5O3nl91QXyakBscnYpi+mnolJzl0g/D2+QQ4Ows7GdVAU3zPl1Kx6Q77s5qMhOxkiUbzOleAyh6x3gxugUcvJz8P9ED4v5F8ECt/kM6seuz87rK5Tu3EfRqDLzyHg5cdZ6qgkvA+ZIf5MblfxP6yIXfPzJmjBTZ1CCJLhgkjUAQMSNTJYUErgH8qpK9MGd3PSkapFRNKeiwNLP451AmYLhgrZwcFArnjWKtSKKB2GtMN+gdJiUg==
    admin-user: AgDBhTjb0RS8G1WH2mPxgLZm/8a2bESX+QxCNARb2yfmacPKBn65/iDww9bmAE8IiXSrGY7mDmiZ0fej8ibN59ZApdy5OE4DcvGvPPjYCAcjRgjx1bu5DRQYmNBtHcFlZX2cqtqFaayFciBlc3gur03Z0M6MktnIHd4xaH3LZhJpps18uNxWMrW3GphUUdppeMKiNhBLWP7ZZwvr9q+GsaNE3vosd0uFnI0xdPi0qOoh/BOrnjceVpES5xbdnvM98rBUnIA+fbSqgIMiG9fKFrgKTm9PqrLBkOxoSrtfI0N+EozH+3RXiGXtVvIPtS1Z5pZLJvfa9q8H0E1i7Qy+0/kc72nEEIayS7eT5DsgZjTgIxuz3m1t92w9tBDGjm5CFuSvezrx+YW9dGMDkWC5Io6tHzYIwI1NsJaDpUvu1Utiya/7voxFldyL2uwEzTox6YQvpYHri93FHz/tdpV6qeRDIk3TSqN17BOl8Ap5ZgTgaAV5PpyhU7oXcwM1OUCKEzHofTNFxKQnS+NGypi2uepZe1+M22PtcAIyVSsgI6ifROx1B9l+uXNm66TkfrLt+QHxKseDwDctqMiVsLlq2xaVhIwWDqoj5E1774M4fqo6/wIwdjC4CxGvq7RQmnCicIBxH3FlimUMs/WvcjKO3f1UsX1MpR1m9H95pqeYQKYFxQmcIWLju+8A/6TyTHUWc3NvMSczAw==
