kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgARtxnPvhM0wgYWCXq69LDLE8oWoiHh5mAL+8bk6UxDcdwnhS7VqQhMzp4ErLnSJnb1j7zQ3rDJmMw7l3fJfSmcJlDGYVhrxJ02hhMaq3LH1OZHAuViqExfhPyFrQodcGKkGj/Ddi2NXGoCbWmb65qv9m7m4ie0aFZgYuzD6dkHy4uctTo5wz7hpB4pjom/VC7a6U4/SEwHtfnZlf8nPUGW3mHpTA/E6BWZ1Vt1Xc1lP0xJAwUSy261IwiHR5QZUyHPFel9ddFCX1CBvIlsb2XpPB7sjajow9LqOsi4oZ95UPcMTwPwdtVRst5zhOgdpO5d/XyfRKbQp2nytu7Wo6jcPFSvcvSeoCIp+4XJf6EzAeLDNwQz1sikUcrh+FQl0rd7tuccTAO4DxUReCUnZp6qx9oIpSYXeXeKCgj63WqaDlia8WBon84/H0VFTQIX4JPMaFNwmW+NuzU5GHaGqkDkyZUwzvKu0kvPm//5kYexbowkk/BfJjQvwCcWPoBwYrPNYLcMendCJzVptiRPg5+zb2pXebYjlLeGsr5fUpPeBrHbbkXAxwiSwuUReR2kLovKOBp0nkz27SuwK24hciJOr++jSWq/Arstuctdw1ui8aNa/9OIaxo7OuOjXe+qJRKYkmO8NmU8IePBh/PqrrDTpfsX93Rkq50tPM6uIaLg/hqFseIV30bYDG2lTAWVoFzUhL6vtg==
    admin-user: AgBMuEi5WPZshgM6J5zo0aAhCat1k0Seb5SDg/Z3yi7H0XRxSKYaQ6EN4fslMdpQvIECHFoQzYq8xNuEhuXouAlSU9R5h4tOJT1/GsX3clv3LFmKB0GtNwm66wqMkujmLhV6C1/mhkGm/5uUQUG2WbXx6bM6S1lqWo/lDfmVuB1DS3lErr81h5eu6Ig905KQVCLWio5W/dpP5twhwRuArMFpACBN+HzVVp9sS68Hxf5RGuE5tgwuv28JSFast35ipuGsGRLB/j0K6V7xPDKt7JFqaMY6gg7bdRU2CHj5mS5gDRMizzqYwCWSExfi69afqmKxctbQOqZyE4EFoQbMLiPajg0CshW81GhhedFKlUSkY+yq6HPtSeHNrLf+LfidQAgokCSs5BK/2cfM6nLYeUyueoLSsXFl32J4BRWiOLIt+2+ijWp68QSx5/H8GTj/vrUUPo9Okz5JCClrzQaE2kSS+ua2TYkv8N6CJHgzBQASNIDb2opysSJHYwnQkA4Dd1q7IKhI5nanEOxALqmdRP+mWoxu01bR8GPp4XDSks7heN1Ox+KSEDerke6iNzg2w0VkYUNRSGxKiYbN8ZdxYYYjNSwMDz34v6WODoIjN8CyrUsVRchsUwQRA5A3iRq9bWZSk9mQ+CsdyGDLLX1nY7QgV+GE/wGAhWIj8ePlxWOrYDtxusreAhv/L9ke9uLONjJM8hz6pA==
