kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgBjW4+iwEFJfQJY+jzpPezi6k5mc78ulsGEhUHoJHNcaWZSgV6NYpOEDuAURVrLTQb+YjKeFWVcDql4jfzAgsu/IyBKXhPwX2CMPeEpcV9ag4/BIRDyrHrmRwNxmoH8TqkXBZmjkbm++LIFu1H5YnuZkY3rT7oezPQC6+xTdRMavWF4xZUveLp1fNUO+ICWlleAYZuZZSx57jFKiyRoLAn9ew3bzy19SmnrA8lZVbbxS1jehmvK4m0T4NOD/KsIHqwiAnR6mhoboi7LHv43WXMUfNqwQZdYeZmi3oO9ZFYTVLS0tZXNvYdvlBmSfswROxdDFwCKWYggW0yUMKae3rfo6zouvyrR4GItdga7ph9VUVU6ANeyOD4Si8zGAjWdcGZEvJDCBAdMaEm1kt6VANtDYC1dkxYlPwjmPykCwnnNt+HMle/EeGw4f1HUvXwJoq8ROsxQaUxNN3eCIGn8LvO1D1V04VqhePR8Cm7PqcxkvTcX849ZUrbCZkhZzpqDNhD505OTk5h5jwxsVWLhfVv4wQAl3p4sVSbmhRKEs70SS0l1oMRd5B9o3uwu1T3ReYmKSzREDMyM+sABrc4dpQ52ldEvo+n2HO3GO4utWgRXaOa+uShZLy22ZxHNHTtmQ+H9hYWixO3I6FAen5NJrTDS3IbIAY4M6cXTLhwMxC3/H9d9eFkTN5iAG6/Fkt/6/+5f0cP7HA==
    admin-user: AgBtRErW0QFuVP/tfaur/YpEE6d9ysrqyiFOSmgj0WJWMY33NVFtM520QanjCYvC4TkNM5KkrEVjR7p2vm+CdmFUZr8TUutKcSX8J+/qUeIzFN1c48KHhU9FrbF1wWmXL6VzZ3zsg7sax8ztrebOXKlI1nwcHETyCGqUiIEQ6sxFpHPcN+1r7oSWb/+QA/nRCSqnBwvn7HyRz4pnRMgsdRtvVC4TU4SwjlEIqCetsxAy1/P4ISQvqzr2rj78IWaQcY1cbLO0Teks0DD84ak5QxIV7UB8wcP3yHoPuhdg2Qsm/gBewW01IN25DiOhCdkICL4FMlWGgezjc0IQ31FdyKWKbwnqXz6iaLeI1D5raqSFhXeqz2Mh5JI2P2qklH/x0iVgENvedEUVRsISC+yojyilOumcq9p3F+SV3IINsWrqeiy4WPAXyxOR8NslK1IzXG9Xi/DkPFgRufeVSgB1g9MrV0ihrQReZrxq6QZ/qg7NowfcVo8J2WtlkxWGtLK4vB4keiQ4znBzNSr+dAVbNw+LIVOLFKKroCUyZJluTWluMH9otAj2JKro29Klfc4pfEq0ZirmwHPRB1Tm0ZISxOL7SiT9ljlNcERSsHzAcIHDWRf/nZ/VHzJTe7OsvZrxI83LEfsoIJ7f6uISklyNNuciZ24/1tOTbeYHhrQVz2ulLYycHK+wat3VM8CRdtGUGCmiG1T48Q==
